In [1]:
import numpy as np

#python list
#list  comprehension
#array module(import lib array)
#numpy array:
     zero
     ones
     full
     eye
     arrange
     reshape
     transpose
     indexing

In [13]:
np.__version__

'1.26.4'

In [15]:
np.zeros?
#np then . and click tab 

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [17]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [21]:
arr= np.arange(0,100)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [33]:
np.arange(-100,0)

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [35]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [37]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [3]:
list(range(0,10)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l=[1,2,3,4,5]

In [7]:
l

[1, 2, 3, 4, 5]

#d/f b/w list and array
#list store characters and numeric values 
#array store only numeric values

In [9]:
l2=[x for x in range(0,10)]

In [12]:
l2 #list  comprehension

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l3=[str(x) for x in l2]

In [18]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
l4=[x**2 for x in l2]

In [22]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
type(l4)

list

In [37]:
import array

In [29]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [41]:
arr=array.array('i',l2)

In [43]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
type(arr)

array.array

In [59]:
arr1=array.array('i',[x**2 for x in l2])

In [61]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [63]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [71]:
np.array([1,2,3,6],dtype='float')

array([1., 2., 3., 6.])

In [73]:
np.array([1,2,3,6],dtype='str')

array(['1', '2', '3', '6'], dtype='<U1')

In [75]:
np.array([1,2,3,6],dtype=np.float32)

array([1., 2., 3., 6.], dtype=float32)

In [77]:
l2d=[[1,2,3],[4,5,6]]

In [80]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [117]:
lc2d=[range(i,i+3) for i in [1,3]]

In [121]:
np.array(lc2d)

array([[1, 2, 3],
       [3, 4, 5]])

In [127]:
lc3d=[range(i,i+3) for i in [1,4,7]]

In [129]:
np.array(lc3d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [142]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [148]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [198]:
arr=np.ones([10,10], dtype = int)

In [200]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [202]:
arr[1:9,1:9]=0

In [204]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [206]:
arr[1:9,1:9]=9

In [208]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [210]:
arr[2:8,2:8]=8

In [212]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [214]:
arr[3:7,3:7]=7

In [216]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [218]:
arr[4:6,4:6]=6

In [220]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 6, 6, 7, 8, 9, 1],
       [1, 9, 8, 7, 6, 6, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [224]:
ar=np.arange(0,9,dtype='float').reshape(3,3)

In [226]:
ar[:]=3.14

In [228]:
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [238]:
np.full((3,4),'abc')
#full for all same values in matrix

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [240]:
#identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [246]:
np.transpose(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
import numpy as np

In [5]:
np.full((6,6),'64')

array([['64', '64', '64', '64', '64', '64'],
       ['64', '64', '64', '64', '64', '64'],
       ['64', '64', '64', '64', '64', '64'],
       ['64', '64', '64', '64', '64', '64'],
       ['64', '64', '64', '64', '64', '64'],
       ['64', '64', '64', '64', '64', '64']], dtype='<U2')

In [17]:
#linspace - linearly spaced elements 
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [23]:
np.random.random(3)
#values between 0 to 1

array([0.73699324, 0.25453786, 0.83764173])

In [25]:
np.random.random((2,2))

array([[0.50016082, 0.7095153 ],
       [0.72906845, 0.90293696]])

In [37]:
np.random.normal(0,1,10)
#values with mean 0 and std 1 
#range is impo(loc,scale,size)

array([ 0.34018076,  0.10420654, -0.27847972, -0.48743594, -0.41967663,
       -1.06965814, -0.80863911, -0.8177247 ,  0.97953569,  2.03513889])

In [41]:
np.random.normal(0,1,(2,2))

array([[0.87367083, 0.74546272],
       [0.92460675, 0.78526437]])

In [45]:
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [49]:
np.random.randint(50,100,36)

array([86, 66, 86, 97, 61, 74, 93, 83, 58, 86, 64, 99, 63, 55, 63, 75, 63,
       78, 72, 80, 80, 75, 62, 51, 81, 86, 77, 68, 79, 63, 72, 73, 80, 61,
       78, 60])

In [51]:
np.random.randn?
#mean 0 and var 1

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [53]:
#operation on numpy array

In [59]:
arr=np.random.randint(0,100,20)

In [57]:
arr

array([88,  9, 15, 18, 80, 71, 88, 11, 17, 46,  7, 75, 28, 33, 84, 96, 88,
       44,  5,  4])

In [63]:
#the number of dimantion
arr.ndim

1

In [65]:
arr.size#total elements 

20

In [67]:
arr.shape#how many elements

(20,)

In [69]:
arr.dtype#data type of array

dtype('int32')

#array indexing

In [81]:
arr1 = np.random.randint(0,40,10)

In [83]:
arr1

array([18, 14, 15, 17, 25, 17, 32, 17, 16, 26])

In [85]:
arr1[0]

18

In [91]:
arr1[4]

25

In [89]:
arr1[-1]

26

In [93]:
arr1[:4]

array([18, 14, 15, 17])

In [95]:
arr1[4:]

array([25, 17, 32, 17, 16, 26])

In [97]:
arr1[4:7]

array([25, 17, 32])

In [109]:
arr1[3]=45

In [111]:
arr1

array([18, 14, 15, 45, 25, 17, 32, 17, 16, 26])

In [66]:
import numpy as np

In [78]:
arr1 = np.random.randint(0,40,10)

In [80]:
arr1

array([ 9,  8,  9, 27, 20, 37,  9, 21, 11, 33])

In [74]:
arr1[2:6:2]

array([ 7, 11])

In [17]:
arr1[2:]

array([23, 18,  5, 29,  6,  2, 16, 14])

In [19]:
arr1[2:10:2]

array([23,  5,  6, 16])

In [21]:
arr1[::2]

array([ 7, 23,  5,  6, 16])

In [23]:
arr1[::-1]
#reverse

array([14, 16,  2,  6, 29,  5, 18, 23, 12,  7])

In [25]:
arr1[::-2]

array([14,  2, 29, 18, 12])

In [39]:
arr2 =np.arange(0,25).reshape(5,5)

In [41]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr2[0,1:4]
#slice[row no:col no+1]

array([1, 2, 3])

In [45]:
arr2[0,1]
#single element[rowno:colno]

1

In [47]:
arr2[2,1]

11

In [49]:
arr2[3,3]

18

In [51]:
arr2[2,4]

14

In [55]:
arr2[0:3,1]

array([ 1,  6, 11])

In [57]:
arr2[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [61]:
arr2[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [67]:
arr2[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [69]:
arr2[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [71]:
arr2[::1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr2[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [75]:
arr2[::,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [81]:
arr2[::-1,::]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [83]:
arr2[::,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

In [1]:
import numpy as np

In [3]:
arr4 =np.arange(0,64).reshape(8,8)

In [5]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [83]:
np.random.random(1)

array([0.64157366])

In [16]:
arr5= np.ones([10,10])

In [18]:
arr5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr5[1:9,1:9]=0

In [30]:
arr5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
a = np.arange(1,10).reshape(3,3)

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [31]:
sa=a[1:3,1:3]
sa#shallow copy

array([[5, 6],
       [8, 9]])

In [72]:
sa[1,1]=5

In [74]:
sa

array([[19, 16],
       [ 8,  5]])

In [44]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 19]])

In [33]:
a[1,2]=16

In [35]:
a

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [37]:
sa

array([[ 5, 16],
       [ 8,  9]])

In [84]:
a[:2,:2]

array([[11,  2],
       [ 4, 19]])

In [78]:
#deep copy
a[0,0]=11
a

array([[11,  2,  3],
       [ 4, 19, 16],
       [ 7,  8,  5]])

In [43]:
da=a[:2,:2].copy()
da

array([[1, 2],
       [4, 5]])

In [45]:
da

array([[1, 2],
       [4, 5]])

In [47]:
da[1,1]

5

In [49]:
da[1,1]=15
da

array([[ 1,  2],
       [ 4, 15]])

In [51]:
a

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [53]:
a3=[1,2,3,4]
a3

[1, 2, 3, 4]

In [55]:
a3=np.arange(1,5).reshape(2,2)

In [57]:
a3

array([[1, 2],
       [3, 4]])

In [59]:
a3.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [122]:
a3=np.arange(0,9).reshape(3,3)
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
a3=np.arange(0,9).reshape(1,9)
a3

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [134]:
a3.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [136]:
a3.ravel()#3d and 2d array convert in 1d array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
a3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [142]:
a3.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [156]:
ar1=a3[:,np.newaxis]
ar1

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])

#concatenation, joining of two arrays

In [158]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

In [61]:
np.concatenate([sa,da])

array([[ 5, 16],
       [ 8,  9],
       [ 1,  2],
       [ 4, 15]])

In [63]:
ca=np.concatenate([sa,da],axis=1)#axis to specify row 0/ and column 1
ca

array([[ 5, 16,  1,  2],
       [ 8,  9,  4, 15]])

In [11]:
a9=np.array([[1,1,1]])
a9

array([[1, 1, 1]])

In [15]:
a10=np.array([[1,1,1,1]])
a10

array([[1, 1, 1, 1]])

In [65]:
np.concatenate([ca,a10])# for row no of col are equal 
                       #for col no of row are equal

array([[ 5, 16,  1,  2],
       [ 8,  9,  4, 15],
       [ 1,  1,  1,  1]])

In [ ]:
#row h stack
#col v stack

In [1]:
import numpy as np

In [94]:
#Stack arrays in sequence vertically (row wise).
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])

In [96]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [98]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [104]:
ar=np.array([[1,3],
            [4,5]])
ar

array([[1, 3],
       [4, 5]])

In [112]:
ar2=ar[np.newaxis]
ar2

array([[[1, 3],
        [4, 5]]])

In [108]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [110]:
x

array([1, 2, 3])

#np.split
#np.vsplit
#np.hsplit

In [129]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [131]:
np.split(a,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [139]:
np.split(a,[1,4])
#if we want split row wise or column wise so add 3rd element is axis.

[array([1]), array([2, 3, 4]), array([5])]

In [141]:
np.split(a,[1,2,4])

[array([1]), array([2]), array([3, 4]), array([5])]

In [153]:
ar3=np.arange(1,9).reshape(2,4)
ar3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
np.vsplit(ar3,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [157]:
np.hsplit(ar3,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [159]:
np.hsplit(ar3,[2,3])

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [161]:
np.sum(ar)

13

In [163]:
np.sum(ar,axis=0)

array([5, 8])

In [165]:
np.sum(ar,axis=1)

array([4, 9])

In [167]:
np.max(ar)

5

In [169]:
np.min(ar)

1

In [171]:
np.argmin(ar)
#index of min element

0

In [173]:
np.argmax(ar)

3

In [175]:
i=-5

In [177]:
np.abs(i)

5

In [179]:
np.var(ar)
#variance

2.1875

In [181]:
np.std(ar)
#standard deviation

1.479019945774904

In [185]:
np.median(ar)

3.5

In [187]:
np.prod(ar)
#factorial

60

#hstack
#vstack
#split
#hsplit
#vsplit
#aggreation

In [135]:
import numpy as np

In [7]:
a=np.arange(5)
a
b=np.full(5,5)
print(a,b)

[0 1 2 3 4] [5 5 5 5 5]


In [9]:
a+b

array([5, 6, 7, 8, 9])

In [13]:
c=np.full(2,3)[:,np.newaxis]
c

array([[3],
       [3]])

In [15]:
b+c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [27]:
m=np.full(2,3)
n=np.full(2,1)[:,np.newaxis]
s=m+n
print(n)
display(m+n,s)
display(s+5)
#broadcasting ex matrix is 1x2 and 2x1 =2x2

[[1]
 [1]]


array([[4, 4],
       [4, 4]])

array([[4, 4],
       [4, 4]])

array([[9, 9],
       [9, 9]])

In [53]:
o=np.ones((3,3))
a=np.arange(3)
display(o,a)
display(o+a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [55]:
a>1

array([False, False,  True])

In [57]:
a==2

array([False, False,  True])

In [59]:
a<1

array([ True, False, False])

In [61]:
a<-1

array([False, False, False])

#ASSIGMENT-1

In [1]:
import numpy as np

In [221]:
#2.Create an array of 10 zeros 
zeroarray=np.zeros(10)
zeroarray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [223]:
#3.Create an array of 10 ones  
onesarray=np.ones(10)
onesarray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [225]:
#4.Create an array of the integers from 10 to 50 
integerarray=np.arange(10, 51)
integerarray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [227]:
#5.Create an array of all the even integers from 10 to 50
even_array=np.arange(10, 51, 2)
even_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [229]:
#6.Create a 3x3 matrix with values ranging from 0 to 8 
A1=np.arange(0,9).reshape(3,3)
A1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [233]:
#7.Create a 3x3 identity matrix 
A2=np.eye(3,3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [237]:
#8. use NumPy to generate a random number between 0 to 1
random_number=np.random.rand(3)
random_number

array([0.86400257, 0.23193662, 0.2809262 ])

In [241]:
#9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution  
random_array1 = np.random.randn(25)
random_array1

array([-0.53440906, -0.72826779,  0.98681451, -1.49580251,  1.36176893,
       -2.09496283, -0.30678278,  0.60941239, -1.22656278,  1.02499428,
        0.8493212 ,  0.47793336, -0.95375908, -0.07042205,  2.07895413,
       -0.71551285,  0.0371595 , -1.81961713, -1.25185262, -0.49519268,
        2.15748638,  0.18668134, -0.45726042, -0.77058391,  1.241607  ])

In [253]:
#10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1 
linearelements = np.linspace(0.01, 1, 100).reshape(10,10)
linearelements 

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [255]:
#11. Create an array of 20 linearly spaced points between 0 and 1
linear2 = np.linspace(0, 1, 20)
linear2 

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [265]:
#12.Create a 5x5 matrix as  

A4 = np.array([[ 1,  2,  3,  4,  5], 
               [ 6,  7,  8,  9, 10], 
               [11, 12, 13, 14, 15], 
               [16, 17, 18, 19, 20], 
               [21, 22, 23, 24, 25]])
A4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [273]:
#find following using slicing 
submatrix = A4[1:4, 1:5]
submatrix 

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [277]:
#b.20
b=A4[3, 4]
b

20

In [283]:
# c
submatrixc = A4[1:4, 1]
submatrixc

array([ 7, 12, 17])

In [287]:
#d.array([21, 22, 23, 24, 25]) 
d = A4[4]
d

array([21, 22, 23, 24, 25])

In [293]:
#e.
e = A4[3:5]
e

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [295]:
#13. Get sum of all values in matrix
sum=np.sum(A4)
sum

325

In [297]:
#14.Get sum of all the columns in matrix
sumcolumnwise=np.sum(A4,axis=0)
sumcolumnwise

array([55, 60, 65, 70, 75])

In [301]:
#15. Get Standard deviation , varience , minimum, maximum from matrix row wis.
Standarddeviation=np.std(A4,axis=1)
Standarddeviation

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [303]:
varience=np.var(A4,axis=1)
varience 

array([2., 2., 2., 2., 2.])

In [305]:
minimum=np.min(A4,axis=1)
minimum

array([ 1,  6, 11, 16, 21])

In [307]:
maximum=np.max(A4,axis=1)
maximum

array([ 5, 10, 15, 20, 25])

In [311]:
#16.create 2 d matrix with all border values nan and
A5=np.zeros((5,5))
A5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [313]:
A5[0, :] = np.nan         
A5

array([[nan, nan, nan, nan, nan],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [315]:
A5[-1, :] = np.nan         
A5

array([[nan, nan, nan, nan, nan],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [nan, nan, nan, nan, nan]])

In [317]:
A5[:, 0] = np.nan          
A5

array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.],
       [nan, nan, nan, nan, nan]])

In [319]:
A5[:, -1] = np.nan
A5

array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])

#ASSIGMENT-2

In [65]:
#1.Create 1-D, 2-D and 3-D numpy array
array1d = np.arange(1, 3)
array1d
array2d = np.arange(1,10).reshape(3,3)
array2d
array3d = np.arange(1,19).reshape(3,2,3)
array3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [67]:
#2. Print data type of array. 
array1d.dtype

dtype('int32')

In [77]:
#3.Print shape and dimensions of all the three different array.
array1d.ndim
array1d.shape


(2,)

In [79]:
array2d.ndim
array2d.shape

(3, 3)

In [81]:
array3d.ndim
array3d.shape

(3, 2, 3)

In [83]:
#4.Create another 1-D array of 12 elements filled with zero 
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
#5.Create another 2-D array elements filled with ones. 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [139]:
#6.Create a 1-D array known as Maths Marks out of 100 having 20 elements.
Maths_Marks = np.array([85, 90, 78, 92, 88, 76, 95, 89, 84, 91,
                        87, 93, 82, 79, 86, 94, 77, 83, 80, 96])
print(Maths_Marks)


[85 90 78 92 88 76 95 89 84 91 87 93 82 79 86 94 77 83 80 96]


In [89]:
#7.Sort the above array in ascending and descending order. 
array = [5,2,8,1,3]
array

[5, 2, 8, 1, 3]

In [91]:
ascending = sorted(array)
ascending

[1, 2, 3, 5, 8]

In [93]:
descending = sorted(array,reverse=True)
descending

[8, 5, 3, 2, 1]

In [213]:
#8.Create a copy of sorted array to another variable by deep copying. 
D1 = np.array([42, 17, 8, 99, 23, 56, 78])
D1

array([42, 17,  8, 99, 23, 56, 78])

In [217]:
sortedarray = np.sort(D1)
sortedarray

array([ 8, 17, 23, 42, 56, 78, 99])

In [219]:
deepcopyarray = sortedarray.copy()
deepcopyarray

array([ 8, 17, 23, 42, 56, 78, 99])

In [99]:
#9. Create 2-D array of 5x5 which is an identity matrix and then convert 1D.
a1=np.eye(5,5)
a1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
a1.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [105]:
#10.Create 2-D array of 3x3. Add one more row to it. 
a9=np.array([[1,1,1]])
a9
arr7=np.arange(0,9).reshape(3,3)
arr7
np.concatenate([arr7,a9])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 1, 1]])

In [145]:
#11.Split above array created vertically and horizontally.
split=np.arange(0,20).reshape(4,5)
split

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [151]:
vertically=np.vsplit(split,4)
vertically

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [169]:
horizontally=np.hsplit(split,5)
horizontally

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [173]:
#12.Create 4x4 identity matrix. Add 4 to each element.
identity=np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [177]:
modify=identity+4
modify

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [183]:
#13. Create 1-D array. Initialize with floating point values. Display its ceil,floor and round (with 2 decimal’s). 
floatarray= np.array([3.1415, 2.7182, 1.4142, 9.8066, 6.626, 7.389])
floatarray

array([3.1415, 2.7182, 1.4142, 9.8066, 6.626 , 7.389 ])

In [187]:
ceilarray=np.ceil(floatarray)
ceilarray

array([ 4.,  3.,  2., 10.,  7.,  8.])

In [191]:
floorarray=np.floor(floatarray)
floorarray

array([3., 2., 1., 9., 6., 7.])

In [193]:
roundarray=np.round(floatarray)
roundarray

array([ 3.,  3.,  1., 10.,  7.,  7.])

In [107]:
#14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.
a11=np.arange(0,25).reshape(5,5)
a11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [195]:
np.min(a11,axis=0)

array([0, 1, 2, 3, 4])

In [199]:
np.max(a11,axis=0)

array([20, 21, 22, 23, 24])

In [201]:
np.var(a11,axis=0)

array([50., 50., 50., 50., 50.])

In [203]:
np.std(a11,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [205]:
#15.Create a null vector of size 10 with 6th value filled with 200. 
nullvector=np.zeros(10)
nullvector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [209]:
nullvector[5]=200
nullvector

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [5]:
#16.Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
array1d=np.arange(100, 151)
array1d

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [15]:
#17.Reverse the above vector.
reverse=array1d[::-1]
reverse

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [17]:
#18. Create a 5x5 matrix with values ranging from 0-24 using some function.
matrix1 = np.arange(25).reshape(5, 5)
matrix1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
#19.Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
H1 = np.array([1, 0, 2, 0, 0, 4, 0, 8])
H1

array([1, 0, 2, 0, 0, 4, 0, 8])

In [21]:
nonzero=np.nonzero(H1)
nonzero

(array([0, 2, 5, 7], dtype=int64),)

In [23]:
#20.Create a 10x10 matrix with 1 on the borders and 0 inside.
arr9= np.ones([10,10])
arr9

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
arr9[1:9,1:9]=0
arr9

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
#21.Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
checkerboard = np.zeros((8,8),dtype=int)
checkerboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1  
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [84]:
#22.Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
matrix1 = np.random.randint(1, 11,(3, 3))
matrix1

array([[1, 8, 7],
       [6, 8, 4],
       [7, 5, 4]])

In [82]:
matrix2 = np.random.randint(1,11,(3, 3))
matrix2

array([[ 6,  1,  1],
       [ 9, 10,  3],
       [ 9,  9,  1]])

In [86]:
addition = np.add(matrix1, matrix2)
addition

array([[ 7,  9,  8],
       [15, 18,  7],
       [16, 14,  5]])

In [90]:
subtraction = np.subtract(matrix1, matrix2)
subtraction

array([[-5,  7,  6],
       [-3, -2,  1],
       [-2, -4,  3]])

In [92]:
multiplication = np.multiply(matrix1, matrix2)
multiplication

array([[ 6,  8,  7],
       [54, 80, 12],
       [63, 45,  4]])