In [1]:
import numpy as np

#python list
#list  comprehension
#array module(import lib array)
#numpy array:
     zero
     ones
     full
     eye
     arrange
     reshape
     transpose
     indexing

In [13]:
np.__version__

'1.26.4'

In [15]:
np.zeros?
#np then . and click tab 

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [17]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [21]:
arr= np.arange(0,100)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [33]:
np.arange(-100,0)

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [35]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [37]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [3]:
list(range(0,10)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l=[1,2,3,4,5]

In [7]:
l

[1, 2, 3, 4, 5]

In [ ]:
#d/f b/w list and array
#list store characters and numeric values 
#array store only numeric values

In [9]:
l2=[x for x in range(0,10)]

In [12]:
l2 #list  comprehension

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l3=[str(x) for x in l2]

In [18]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
l4=[x**2 for x in l2]

In [22]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
type(l4)

list

In [37]:
import array

In [29]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [41]:
arr=array.array('i',l2)

In [43]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
type(arr)

array.array

In [59]:
arr1=array.array('i',[x**2 for x in l2])

In [61]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [63]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [71]:
np.array([1,2,3,6],dtype='float')

array([1., 2., 3., 6.])

In [73]:
np.array([1,2,3,6],dtype='str')

array(['1', '2', '3', '6'], dtype='<U1')

In [75]:
np.array([1,2,3,6],dtype=np.float32)

array([1., 2., 3., 6.], dtype=float32)

In [77]:
l2d=[[1,2,3],[4,5,6]]

In [80]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [117]:
lc2d=[range(i,i+3) for i in [1,3]]

In [121]:
np.array(lc2d)

array([[1, 2, 3],
       [3, 4, 5]])

In [127]:
lc3d=[range(i,i+3) for i in [1,4,7]]

In [129]:
np.array(lc3d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [142]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [148]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [198]:
arr=np.ones([10,10], dtype = int)

In [200]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [202]:
arr[1:9,1:9]=0

In [204]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [206]:
arr[1:9,1:9]=9

In [208]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [210]:
arr[2:8,2:8]=8

In [212]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [214]:
arr[3:7,3:7]=7

In [216]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [218]:
arr[4:6,4:6]=6

In [220]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 7, 6, 6, 7, 8, 9, 1],
       [1, 9, 8, 7, 6, 6, 7, 8, 9, 1],
       [1, 9, 8, 7, 7, 7, 7, 8, 9, 1],
       [1, 9, 8, 8, 8, 8, 8, 8, 9, 1],
       [1, 9, 9, 9, 9, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [224]:
ar=np.arange(0,9,dtype='float').reshape(3,3)

In [226]:
ar[:]=3.14

In [228]:
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [238]:
np.full((3,4),'abc')
#full for all same values in matrix

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [240]:
#identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [246]:
np.transpose(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])